import "./globals.css";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"

import { FloatingNav } from "@/components/ui/floating-navbar";
import { IconHome, IconHanger, IconShoe, IconHandStop, IconDiamond } from "@tabler/icons-react";
const navItems = [
  {
    name: "Inicio",
    link: "/",
    icon: <IconHome />,
  },
  {
    name: "Techwear",
    link: "/techwear",
    icon: <IconHanger />,
  },
  {
    name: "Footwear",
    link: "/footwear",
    icon: <IconShoe />,
  },
  {
    name: "Handwear",
    link: "/handwear",
    icon: <IconHandStop />,
  },
  {
    name: "Jewelry",
    link: "/jewelry",
    icon: <IconDiamond />,
  },
];



const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased bg-black",
          fontSans.variable
        )}
      >
        <FloatingNav navItems={navItems} />
        {children}</body>
    </html>
  );
}
